## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial columns 'EIN' and 'NAME'
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [3]:
# Determine the number of unique values in each column
unique_value_counts = application_df.nunique()

# Print the unique value counts
print(unique_value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Determine a cutoff value for the number of counts
cutoff_value = 500

# Create a list of application types to be replaced with "Other"
application_types_to_replace = list(application_type_counts[application_type_counts < cutoff_value].index)

# Replace in the dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# Filter CLASSIFICATION value counts greater than 1
classification_counts_gt_1 = classification_counts[classification_counts > 1]
print(classification_counts_gt_1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Determine a cutoff value for the number of counts
cutoff_value = 100

# Create a list of classifications to be replaced with "Other"
classifications_to_replace = list(classification_counts[classification_counts < cutoff_value].index)

# Replace in the dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure binning was successful
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_value_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric using pd.get_dummies
application_df = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])

# Display the updated DataFrame
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
# Split the preprocessed data into features (X) and target (y) arrays
X = application_df.drop(columns=['IS_SUCCESSFUL'])
y = application_df['IS_SUCCESSFUL']

# Split the data into a training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, input_dim=len(X_train_scaled[0]), activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4000

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6461 (25.24 KB)
Trainable params: 6461 (25.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, validation_data=(X_test_scaled, y_test), verbose=2)

Epoch 1/100
858/858 - 1s - loss: 0.5697 - accuracy: 0.7195 - val_loss: 0.5616 - val_accuracy: 0.7259 - 688ms/epoch - 802us/step
Epoch 2/100
858/858 - 0s - loss: 0.5520 - accuracy: 0.7297 - val_loss: 0.5615 - val_accuracy: 0.7252 - 448ms/epoch - 522us/step
Epoch 3/100
858/858 - 0s - loss: 0.5487 - accuracy: 0.7319 - val_loss: 0.5587 - val_accuracy: 0.7271 - 417ms/epoch - 486us/step
Epoch 4/100
858/858 - 0s - loss: 0.5476 - accuracy: 0.7321 - val_loss: 0.5574 - val_accuracy: 0.7287 - 417ms/epoch - 486us/step
Epoch 5/100
858/858 - 0s - loss: 0.5457 - accuracy: 0.7341 - val_loss: 0.5636 - val_accuracy: 0.7188 - 417ms/epoch - 486us/step
Epoch 6/100
858/858 - 0s - loss: 0.5451 - accuracy: 0.7336 - val_loss: 0.5551 - val_accuracy: 0.7276 - 418ms/epoch - 487us/step
Epoch 7/100
858/858 - 0s - loss: 0.5445 - accuracy: 0.7317 - val_loss: 0.5555 - val_accuracy: 0.7284 - 420ms/epoch - 490us/step
Epoch 8/100
858/858 - 0s - loss: 0.5440 - accuracy: 0.7343 - val_loss: 0.5595 - val_accuracy: 0.7257 - 420ms/epoch - 490us/step
Epoch 9/100
858/858 - 0s - loss: 0.5429 - accuracy: 0.7334 - val_loss: 0.5580 - val_accuracy: 0.7270 - 421ms/epoch - 491us/step
Epoch 10/100
858/858 - 0s - loss: 0.5428 - accuracy: 0.7345 - val_loss: 0.5555 - val_accuracy: 0.7276 - 415ms/epoch - 484us/step
Epoch 11/100
858/858 - 0s - loss: 0.5422 - accuracy: 0.7346 - val_loss: 0.5544 - val_accuracy: 0.7299 - 419ms/epoch - 488us/step
Epoch 12/100
858/858 - 0s - loss: 0.5415 - accuracy: 0.7357 - val_loss: 0.5570 - val_accuracy: 0.7249 - 419ms/epoch - 488us/step
Epoch 13/100
858/858 - 0s - loss: 0.5417 - accuracy: 0.7349 - val_loss: 0.5531 - val_accuracy: 0.7284 - 418ms/epoch - 488us/step
Epoch 14/100
858/858 - 0s - loss: 0.5409 - accuracy: 0.7345 - val_loss: 0.5566 - val_accuracy: 0.7283 - 420ms/epoch - 490us/step
Epoch 15/100
858/858 - 0s - loss: 0.5405 - accuracy: 0.7360 - val_loss: 0.5552 - val_accuracy: 0.7255 - 419ms/epoch - 488us/step
Epoch 16/100
858/858 - 0s - loss: 0.5400 - accuracy: 0.7364 - val_loss: 0.5545 - val_accuracy: 0.7297 - 419ms/epoch - 488us/step
Epoch 17/100
858/858 - 0s - loss: 0.5400 - accuracy: 0.7361 - val_loss: 0.5553 - val_accuracy: 0.7277 - 420ms/epoch - 489us/step
Epoch 18/100
858/858 - 0s - loss: 0.5396 - accuracy: 0.7351 - val_loss: 0.5562 - val_accuracy: 0.7264 - 417ms/epoch - 486us/step
Epoch 19/100
858/858 - 0s - loss: 0.5392 - accuracy: 0.7364 - val_loss: 0.5583 - val_accuracy: 0.7245 - 419ms/epoch - 488us/step
Epoch 20/100
858/858 - 0s - loss: 0.5392 - accuracy: 0.7368 - val_loss: 0.5554 - val_accuracy: 0.7274 - 419ms/epoch - 488us/step
Epoch 21/100
858/858 - 0s - loss: 0.5389 - accuracy: 0.7369 - val_loss: 0.5543 - val_accuracy: 0.7264 - 420ms/epoch - 489us/step
Epoch 22/100
858/858 - 0s - loss: 0.5383 - accuracy: 0.7377 - val_loss: 0.5543 - val_accuracy: 0.7278 - 418ms/epoch - 487us/step
Epoch 23/100
858/858 - 0s - loss: 0.5384 - accuracy: 0.7375 - val_loss: 0.5552 - val_accuracy: 0.7281 - 420ms/epoch - 490us/step
Epoch 24/100
858/858 - 0s - loss: 0.5382 - accuracy: 0.7370 - val_loss: 0.5557 - val_accuracy: 0.7268 - 418ms/epoch - 487us/step
Epoch 25/100
858/858 - 0s - loss: 0.5378 - accuracy: 0.7367 - val_loss: 0.5540 - val_accuracy: 0.7270 - 418ms/epoch - 488us/step
Epoch 26/100
858/858 - 0s - loss: 0.5375 - accuracy: 0.7380 - val_loss: 0.5568 - val_accuracy: 0.7270 - 419ms/epoch - 489us/step
Epoch 27/100
858/858 - 0s - loss: 0.5373 - accuracy: 0.7376 - val_loss: 0.5554 - val_accuracy: 0.7255 - 419ms/epoch - 488us/step
Epoch 28/100
858/858 - 0s - loss: 0.5373 - accuracy: 0.7372 - val_loss: 0.5536 - val_accuracy: 0.7281 - 417ms/epoch - 486us/step
Epoch 29/100
858/858 - 0s - loss: 0.5370 - accuracy: 0.7368 - val_loss: 0.5556 - val_accuracy: 0.7258 - 420ms/epoch - 490us/step
Epoch 30/100
858/858 - 0s - loss: 0.5371 - accuracy: 0.7377 - val_loss: 0.5545 - val_accuracy: 0.7243 - 420ms/epoch - 489us/step
Epoch 31/100
858/858 - 0s - loss: 0.5365 - accuracy: 0.7381 - val_loss: 0.5549 - val_accuracy: 0.7262 - 433ms/epoch - 505us/step
Epoch 32/100
858/858 - 0s - loss: 0.5364 - accuracy: 0.7384 - val_loss: 0.5563 - val_accuracy: 0.7258 - 418ms/epoch - 487us/step
Epoch 33/100
858/858 - 0s - loss: 0.5361 - accuracy: 0.7376 - val_loss: 0.5566 - val_accuracy: 0.7261 - 417ms/epoch - 486us/step
Epoch 34/100
858/858 - 0s - loss: 0.5366 - accuracy: 0.7380 - val_loss: 0.5552 - val_accuracy: 0.7284 - 419ms/epoch - 489us/step
Epoch 35/100
858/858 - 0s - loss: 0.5361 - accuracy: 0.7382 - val_loss: 0.5546 - val_accuracy: 0.7267 - 418ms/epoch - 487us/step
Epoch 36/100
858/858 - 0s - loss: 0.5359 - accuracy: 0.7389 - val_loss: 0.5571 - val_accuracy: 0.7274 - 417ms/epoch - 486us/step
Epoch 37/100
858/858 - 0s - loss: 0.5361 - accuracy: 0.7380 - val_loss: 0.5549 - val_accuracy: 0.7276 - 419ms/epoch - 488us/step
Epoch 38/100
858/858 - 0s - loss: 0.5359 - accuracy: 0.7390 - val_loss: 0.5568 - val_accuracy: 0.7230 - 418ms/epoch - 487us/step
Epoch 39/100
858/858 - 0s - loss: 0.5357 - accuracy: 0.7382 - val_loss: 0.5557 - val_accuracy: 0.7265 - 419ms/epoch - 488us/step
Epoch 40/100
858/858 - 0s - loss: 0.5347 - accuracy: 0.7389 - val_loss: 0.5567 - val_accuracy: 0.7243 - 419ms/epoch - 488us/step
Epoch 41/100
858/858 - 0s - loss: 0.5353 - accuracy: 0.7388 - val_loss: 0.5567 - val_accuracy: 0.7251 - 416ms/epoch - 485us/step
Epoch 42/100
858/858 - 0s - loss: 0.5354 - accuracy: 0.7376 - val_loss: 0.5560 - val_accuracy: 0.7258 - 418ms/epoch - 487us/step
Epoch 43/100
858/858 - 0s - loss: 0.5349 - accuracy: 0.7391 - val_loss: 0.5563 - val_accuracy: 0.7255 - 418ms/epoch - 487us/step
Epoch 44/100
858/858 - 0s - loss: 0.5350 - accuracy: 0.7395 - val_loss: 0.5565 - val_accuracy: 0.7290 - 419ms/epoch - 488us/step
Epoch 45/100
858/858 - 0s - loss: 0.5347 - accuracy: 0.7386 - val_loss: 0.5567 - val_accuracy: 0.7265 - 419ms/epoch - 489us/step
Epoch 46/100
858/858 - 0s - loss: 0.5350 - accuracy: 0.7383 - val_loss: 0.5566 - val_accuracy: 0.7261 - 417ms/epoch - 486us/step
Epoch 47/100
858/858 - 0s - loss: 0.5345 - accuracy: 0.7390 - val_loss: 0.5582 - val_accuracy: 0.7281 - 418ms/epoch - 488us/step
Epoch 48/100
858/858 - 0s - loss: 0.5349 - accuracy: 0.7397 - val_loss: 0.5562 - val_accuracy: 0.7271 - 415ms/epoch - 484us/step
Epoch 49/100
858/858 - 0s - loss: 0.5340 - accuracy: 0.7393 - val_loss: 0.5591 - val_accuracy: 0.7264 - 418ms/epoch - 487us/step
Epoch 50/100
858/858 - 0s - loss: 0.5345 - accuracy: 0.7386 - val_loss: 0.5569 - val_accuracy: 0.7258 - 418ms/epoch - 487us/step
Epoch 51/100
858/858 - 0s - loss: 0.5343 - accuracy: 0.7393 - val_loss: 0.5572 - val_accuracy: 0.7259 - 420ms/epoch - 490us/step
Epoch 52/100
858/858 - 0s - loss: 0.5344 - accuracy: 0.7400 - val_loss: 0.5573 - val_accuracy: 0.7292 - 419ms/epoch - 488us/step
Epoch 53/100
858/858 - 0s - loss: 0.5340 - accuracy: 0.7403 - val_loss: 0.5575 - val_accuracy: 0.7264 - 421ms/epoch - 491us/step
Epoch 54/100
858/858 - 0s - loss: 0.5339 - accuracy: 0.7393 - val_loss: 0.5583 - val_accuracy: 0.7222 - 421ms/epoch - 491us/step
Epoch 55/100
858/858 - 0s - loss: 0.5341 - accuracy: 0.7389 - val_loss: 0.5556 - val_accuracy: 0.7273 - 431ms/epoch - 502us/step
Epoch 56/100
858/858 - 0s - loss: 0.5337 - accuracy: 0.7394 - val_loss: 0.5603 - val_accuracy: 0.7261 - 418ms/epoch - 487us/step
Epoch 57/100
858/858 - 0s - loss: 0.5334 - accuracy: 0.7390 - val_loss: 0.5602 - val_accuracy: 0.7267 - 416ms/epoch - 485us/step
Epoch 58/100
858/858 - 0s - loss: 0.5336 - accuracy: 0.7392 - val_loss: 0.5601 - val_accuracy: 0.7264 - 419ms/epoch - 489us/step
Epoch 59/100
858/858 - 0s - loss: 0.5334 - accuracy: 0.7395 - val_loss: 0.5594 - val_accuracy: 0.7265 - 415ms/epoch - 484us/step
Epoch 60/100
858/858 - 0s - loss: 0.5337 - accuracy: 0.7396 - val_loss: 0.5572 - val_accuracy: 0.7271 - 423ms/epoch - 493us/step
Epoch 61/100
858/858 - 0s - loss: 0.5338 - accuracy: 0.7393 - val_loss: 0.5569 - val_accuracy: 0.7259 - 416ms/epoch - 485us/step
Epoch 62/100
858/858 - 0s - loss: 0.5335 - accuracy: 0.7398 - val_loss: 0.5607 - val_accuracy: 0.7267 - 416ms/epoch - 485us/step
Epoch 63/100
858/858 - 0s - loss: 0.5339 - accuracy: 0.7392 - val_loss: 0.5588 - val_accuracy: 0.7270 - 415ms/epoch - 484us/step
Epoch 64/100
858/858 - 0s - loss: 0.5333 - accuracy: 0.7395 - val_loss: 0.5572 - val_accuracy: 0.7267 - 419ms/epoch - 488us/step

Epoch 65/100
858/858 - 0s - loss: 0.5331 - accuracy: 0.7411 - val_loss: 0.5573 - val_accuracy: 0.7232 - 417ms/epoch - 486us/step
Epoch 66/100
858/858 - 0s - loss: 0.5338 - accuracy: 0.7398 - val_loss: 0.5583 - val_accuracy: 0.7257 - 417ms/epoch - 485us/step
Epoch 67/100
858/858 - 0s - loss: 0.5336 - accuracy: 0.7399 - val_loss: 0.5586 - val_accuracy: 0.7258 - 417ms/epoch - 486us/step
Epoch 68/100
858/858 - 0s - loss: 0.5332 - accuracy: 0.7393 - val_loss: 0.5578 - val_accuracy: 0.7229 - 418ms/epoch - 487us/step
Epoch 69/100
858/858 - 0s - loss: 0.5334 - accuracy: 0.7396 - val_loss: 0.5575 - val_accuracy: 0.7259 - 416ms/epoch - 485us/step
Epoch 70/100
858/858 - 0s - loss: 0.5330 - accuracy: 0.7410 - val_loss: 0.5577 - val_accuracy: 0.7259 - 417ms/epoch - 485us/step
Epoch 71/100
858/858 - 0s - loss: 0.5331 - accuracy: 0.7395 - val_loss: 0.5570 - val_accuracy: 0.7273 - 415ms/epoch - 484us/step
Epoch 72/100
858/858 - 0s - loss: 0.5328 - accuracy: 0.7398 - val_loss: 0.5567 - val_accuracy: 0.7270 - 418ms/epoch - 487us/step
Epoch 73/100
858/858 - 0s - loss: 0.5328 - accuracy: 0.7406 - val_loss: 0.5571 - val_accuracy: 0.7273 - 416ms/epoch - 485us/step
Epoch 74/100
858/858 - 0s - loss: 0.5324 - accuracy: 0.7404 - val_loss: 0.5593 - val_accuracy: 0.7271 - 413ms/epoch - 482us/step
Epoch 75/100
858/858 - 0s - loss: 0.5331 - accuracy: 0.7399 - val_loss: 0.5578 - val_accuracy: 0.7257 - 415ms/epoch - 484us/step
Epoch 76/100
858/858 - 0s - loss: 0.5324 - accuracy: 0.7400 - val_loss: 0.5599 - val_accuracy: 0.7252 - 420ms/epoch - 489us/step
Epoch 77/100
858/858 - 0s - loss: 0.5325 - accuracy: 0.7405 - val_loss: 0.5557 - val_accuracy: 0.7286 - 416ms/epoch - 485us/step
Epoch 78/100
858/858 - 0s - loss: 0.5328 - accuracy: 0.7397 - val_loss: 0.5589 - val_accuracy: 0.7286 - 418ms/epoch - 487us/step
Epoch 79/100
858/858 - 0s - loss: 0.5323 - accuracy: 0.7411 - val_loss: 0.5586 - val_accuracy: 0.7264 - 418ms/epoch - 487us/step
Epoch 80/100
858/858 - 0s - loss: 0.5326 - accuracy: 0.7415 - val_loss: 0.5591 - val_accuracy: 0.7267 - 416ms/epoch - 485us/step
Epoch 81/100
858/858 - 0s - loss: 0.5319 - accuracy: 0.7407 - val_loss: 0.5578 - val_accuracy: 0.7264 - 417ms/epoch - 486us/step
Epoch 82/100
858/858 - 0s - loss: 0.5325 - accuracy: 0.7411 - val_loss: 0.5595 - val_accuracy: 0.7265 - 417ms/epoch - 486us/step
Epoch 83/100
858/858 - 0s - loss: 0.5327 - accuracy: 0.7408 - val_loss: 0.5564 - val_accuracy: 0.7280 - 416ms/epoch - 485us/step
Epoch 84/100
858/858 - 0s - loss: 0.5321 - accuracy: 0.7407 - val_loss: 0.5583 - val_accuracy: 0.7242 - 417ms/epoch - 486us/step
Epoch 85/100
858/858 - 0s - loss: 0.5321 - accuracy: 0.7399 - val_loss: 0.5592 - val_accuracy: 0.7265 - 418ms/epoch - 487us/step
Epoch 86/100
858/858 - 0s - loss: 0.5318 - accuracy: 0.7389 - val_loss: 0.5608 - val_accuracy: 0.7258 - 413ms/epoch - 482us/step
Epoch 87/100
858/858 - 0s - loss: 0.5322 - accuracy: 0.7396 - val_loss: 0.5593 - val_accuracy: 0.7264 - 418ms/epoch - 487us/step
Epoch 88/100
858/858 - 0s - loss: 0.5317 - accuracy: 0.7406 - val_loss: 0.5579 - val_accuracy: 0.7261 - 417ms/epoch - 486us/step
Epoch 89/100
858/858 - 0s - loss: 0.5321 - accuracy: 0.7409 - val_loss: 0.5591 - val_accuracy: 0.7262 - 417ms/epoch - 486us/step
Epoch 90/100
858/858 - 0s - loss: 0.5318 - accuracy: 0.7407 - val_loss: 0.5586 - val_accuracy: 0.7277 - 418ms/epoch - 488us/step
Epoch 91/100
858/858 - 0s - loss: 0.5323 - accuracy: 0.7400 - val_loss: 0.5577 - val_accuracy: 0.7258 - 417ms/epoch - 486us/step
Epoch 92/100
858/858 - 0s - loss: 0.5321 - accuracy: 0.7414 - val_loss: 0.5593 - val_accuracy: 0.7267 - 418ms/epoch - 487us/step
Epoch 93/100
858/858 - 0s - loss: 0.5321 - accuracy: 0.7404 - val_loss: 0.5605 - val_accuracy: 0.7261 - 417ms/epoch - 486us/step
Epoch 94/100
858/858 - 0s - loss: 0.5316 - accuracy: 0.7405 - val_loss: 0.5603 - val_accuracy: 0.7241 - 416ms/epoch - 485us/step
Epoch 95/100
858/858 - 0s - loss: 0.5314 - accuracy: 0.7400 - val_loss: 0.5594 - val_accuracy: 0.7265 - 418ms/epoch - 487us/step
Epoch 96/100
858/858 - 0s - loss: 0.5316 - accuracy: 0.7395 - val_loss: 0.5591 - val_accuracy: 0.7252 - 419ms/epoch - 488us/step
Epoch 97/100
858/858 - 0s - loss: 0.5315 - accuracy: 0.7402 - val_loss: 0.5601 - val_accuracy: 0.7257 - 417ms/epoch - 486us/step
Epoch 98/100
858/858 - 0s - loss: 0.5316 - accuracy: 0.7400 - val_loss: 0.5606 - val_accuracy: 0.7251 - 418ms/epoch - 487us/step
Epoch 99/100
858/858 - 0s - loss: 0.5311 - accuracy: 0.7408 - val_loss: 0.5583 - val_accuracy: 0.7296 - 418ms/epoch - 487us/step
Epoch 100/100
858/858 - 0s - loss: 0.5314 - accuracy: 0.7414 - val_loss: 0.5615 - val_accuracy: 0.7289 - 421ms/epoch - 491us/step

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5615 - accuracy: 0.7289 - 84ms/epoch - 390us/step
Loss: 0.5614764094352722, Accuracy: 0.728863000869751

In [18]:
# Define the file path for the model
model_file = "your_model.h5"  # Replace with your desired file name

# Save the model to the HDF5 file
nn.save(model_file)

/Users/mili/anaconda3/lib/python3.11/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(